# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b99cdc5e695749552cfad681f052242aa7e242cc1c68edbd976788d63a601ea7820f52f9ac4ed78b52de0948498eed4efd1195abdc86e28a7ce02bb0cecff3a3

test:
  secret_key_base: 022682ecd71e5c5d9f40c002842a0d9d1319990863cf3f3552705a6f93e3c599744c3d462413842db9fb536f6c4c8c870c8b76ab668d6784bee1b263703dff3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
